# Generated by Django 4.2.6 on 2023-10-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('fact_qlid_data1', models.IntegerField()),
                ('fact_qlid_data2', models.IntegerField()),
                ('fact_qoil_data1', models.IntegerField()),
                ('fact_qoil_data2', models.IntegerField()),
                ('forecast_qlid_data1', models.IntegerField()),
                ('forecast_qlid_data2', models.IntegerField()),
                ('forecast_qoil_data1', models.IntegerField()),
                ('forecast_qoil_data2', models.IntegerField()),
                ('total_qlid', models.IntegerField(null=True)),
                ('total_qoil', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
            },
        ),
    ]
