# Generated by Django 4.2.6 on 2023-10-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='fact_qlid_data1',
            new_name='fact_qliq_data1',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='fact_qlid_data2',
            new_name='fact_qliq_data2',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='forecast_qlid_data1',
            new_name='forecast_qliq_data1',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='forecast_qlid_data2',
            new_name='forecast_qliq_data2',
        ),
    ]
