# Generated by Django 4.2.6 on 2023-10-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_fact_qlid_data1_report_fact_qliq_data1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='total_qlid',
            new_name='total_qliq',
        ),
    ]
